### ISSUE TITLE
OpenAllBags() taints all bag contents

### ISSUE THREAD

**Issue by DDCorkum** [Stanzilla/WoWUIBugs#310]
In the Dragonflight Beta, `/run OpenAllBags()` taints all backpack and bag contents.

Once tainted, right-clicking on any item errors at ContainerFrame.lua:1408 during a call to UseContainerItem().

**Comment by Cidan** [comment]
Slightly related: by using your own ItemButton frames and building your own bag, you can workaround this taint, unless you call `SetBagID()` on the ItemButton, at which point the taint applies. This means this taint, if intentional, is not comprehensive and can be worked around trivially.

**Comment by DDCorkum** [comment]
Here's the short workaround
```lua
for i=1, NUM_CONTAINER_FRAMES do
	for j=1, 36 do
		_G["ContainerFrame"..i.."Item"..j].SetBagID = nop
	end
end
```

However, that causes disastrous results when users combine the bags, indicated by console variable `combinedBags`.

I'm probably playing with fire (aka the settings panel) but here's a crude solution to apply the workaround on login only when the user hasn't combined the bags, and to invite the user to reload the user interface if they alter that setting.

```lua
if ContainerFrameMixin then
	-- To prevent taint in WoW 10.0.0
	
	-- Remove ContainerFrameItemButtonMixin:SetBagID() before it ever gets called, but only when the user is not combining bags
	if not C_CVar.GetCVarBool("combinedBags") then
		for i=1, NUM_CONTAINER_FRAMES do
			for j=1, 36 do
				local frame = _G["ContainerFrame"..i.."Item"..j]
				if frame then
					frame.SetBagID = nop
				end
			end
		end
	end
	
	-- Encouraging the user to reload the UI after turning combined bags on and off.
	local needButton = true
	EventRegistry:RegisterFrameEventAndCallback("USE_COMBINED_BAGS_CHANGED", function()
		if needButton then
			needButton = false
			local btn = CreateFrame("Button", nil, SettingsPanel, "SecureActionButtonTemplate, UIPanelButtonTemplate")
			btn:RegisterForClicks("AnyDown", "AnyUp")
			btn:SetAttribute("type", "macro")
			btn:SetAttribute("macrotext", "/reload")
			btn:SetSize(SettingsPanel.CloseButton:GetSize())
			btn:SetPoint("RIGHT", SettingsPanel.CloseButton, "LEFT", -5, 0)
			btn:SetText(RELOADUI)
			btn.tooltipText = "Reload required for addon compatibility"
		end
	end)
end
```

**Comment by KVLtv** [comment]
I am maintaining an AddOn on Curse called Bagger. As you might derive from the name, this issue affects my AddOn very severely. I'm trying to overcome the taint issue, but haven't had much luck so far. I am only a hobbyist and I have a limited experience in scripting, so everything is a learning process. I came across this post and am intrigued. I would be appreciative if anyone participating, or anyone happening upon this thread, has some helpful advice. I realize [Cidan](https//github/Cidan) offered a solution, but I don't really follow what he means. I've been looking at ..\Interface\FrameXML\ContainerFrame.lua and am unable to see how I could create my own bag without ending up with the taint.

**Comment by Cidan** [comment]
Essentially, you would have to create your own `ItemButton` frames, assign them to items based on the bag contents, and draw your own bag, all from scratch, while leaving out `SetBagID()` for your custom item buttons. It's an immense amount of work if you're not already doing it, so it wasn't really a suggestion. I was trying to illustrate a point that if this taint is intentional, there is a workaround.

**Comment by KVLtv** [comment]
That is probably a bit beyond my needs anyway. It may seem silly, but the only functionality built into my AddOn is to open and close the bags for the few things the game doesn’t. At this time, there are only three event types which my AddOn is required for in World of Warcraft Dragonflight. However, the two most important event types are fired by me quite a lot when I play the game, namely the Banker and the GuildBank. The AddOn does a lot more in Classic, but that’s neither here nor there, As such, the taint from OpenAllBags() was a major setback for me. I am hoping there is a way to get around it by using _G[“exampleframe” .. example] :Show() and _G[“exampleframe” .. example] :Hide by creating some way to call the bags in the exampleframe and identifying them with the example. I’m only guessing, and since the BagID would likely still be a factor, I am not sure if there will be a way to do that without calling the taint, and I have no idea where the taint actually originates.
Thanks,
Karl

On Nov 7, 2022, at 2:42 PM, Antonio Lobato ***@***.***> wrote:

Essentially, you would have to create your own ItemButton frames, assign them to items based on the bag contents, and draw your own bag, all from scratch, while leaving out SetBagID() for your custom item buttons. It's an immense amount of work if you're not already doing it, so it wasn't really a suggestion. I was trying to illustrate a point that if this taint is intentional, there is a workaround.

**Comment by KVLtv** [comment]
Dragonflight introduced a new pair of events: PLAYER_INTERACTION_MANAGER_FRAME_SHOW and PLAYER_INTERACTION_MANAGER_FRAME_HIDE. These two events call to 64 different types of player interactions. I've corrected my AddOn to only do anything if the three types I mentioned above are fired. The code looks like this:

if (event == "PLAYER_INTERACTION_MANAGER_FRAME_SHOW")
	then
		local type = ...
		local retailBag = tonumber(type)
			if retailBag and retailBag == 8     -- 8 is the Banker
			then
				local BankBags = GetNumBankSlots()
				local i
				for i = 0, BankBags do
				OpenBag(NUM_BAG_SLOTS + 1 + i)
				end
			elseif retailBag and retailBag == 10 or retailBag == 53    -- 10 is GuildBanker and 53 is ItemUpgrade
			then
				OpenAllBags()
			end	
end
However, I just now had the game error claiming: AddOn 'Bagger' tried to call the protected function 'UseContainerItem()'.",
The thing is, I had not gone to the bank, or the guild bank, or an upgrade master, so my AddOn had no opportunity to call OpenAllBags() before the error had occurred, so I don't understand how it is that the error took place. I mean, doesn't the code have to actually run first?

**Comment by Jaliborc** [comment]
> Slightly related: by using your own ItemButton frames and building your own bag, you can workaround this taint, unless you call `SetBagID()` on the ItemButton, at which point the taint applies. This means this taint, if intentional, is not comprehensive and can be worked around trivially.

Can you post some references? As to why that specific behaviour?

**Comment by thefowles1** [comment]
@Meorawr do you have confirmation that this has been acknowledged by blizz? Comments on the forums state as of August that it's still not been verified by a blue post.

**Comment by Meorawr** [comment]
Appears to be fixed in 10.2.7 - ContainerFrameItemButtonMixin:SetBagID now assigns through an attribute, rather than directly mucking up a field on the button frame directly.
