### ISSUE TITLE
BAG_UPDATE_DELAYED does not fire for all bags since Wrath 3.4.1

### ISSUE THREAD

**Issue by lordblackadder** [Stanzilla/WoWUIBugs#381]
BAG_UPDATE_DELAYED has been inconsistent since the new WotLK patch. It will only fire when an item is moved within/from/to the default backpack. It does not fire when the default backback is not involved in any way.

Steps to reproduce: 

1. /etrace 
2. move items involving the default backback and it will fire
3. move items in other bags and only BAG_UPDATE will fire

**Comment by Stanzilla** [comment]
Fixed in a future build

**Comment by Stanzilla** [comment]
Fixed in 3.4.1.47800

**Comment by syndenbock** [comment]
Is there also a retail build known where this will be fixed?

**Comment by Xruptor** [comment]
Okay I can confirm that this bug is back now on the Retail servers.  It still isn't working properly.

**Comment by b-morgan** [comment]
I'm looking at my Skillet-Classic fix for missing BAG_UPDATE_DELAYED and I use UNIT_INVENTORY_CHANGED instead. Actually, I think I have both events registered with the function contents duplicated. Not sure what will happen when both are firing so I'll have to check that.

**Comment by mbattersby** [comment]
Confirming that for retail BAG_UPDATE_DELAYED is now only firing for the Backpack (BagID == 0) and no other bags.

**Comment by Stanzilla** [comment]
It should be fixed in the next retail and classic builds, no ETA on when they will land though.

**Comment by b-morgan** [comment]
Can you think of any downside to leaving the timer in place (start in BAG_UDATE, cancel in BAG_UPDATE_DELAYED)?

**Comment by Meorawr** [comment]
For retail this is fixed in 10.0.5.47884 on the PTR; I'd expect that'll go live about 10 minutes after I get in bed specifically to trigger a build alert ping on discord that wakes me back up and makes me check my phone.

**Comment by syndenbock** [comment]
This seems to be fixed on live Retail servers since today.
